port: 4002
description: "This is the Fieldwork & Professional Practice web site."
# The base URL of your site when hosted
# The subdirectory for your repository (leave empty for root-level sites)
url: "https://alainparadis.github.io"
baseurl: "/WIL"
theme: null
exclude:
  - vendor
  - tmp
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
twitter_username: alainparadis
github_username:  alainparadis
collections:
  posts:
    output: true
